/**
 * Top-traffic UK postcode outcodes for programmatic SEO.
 * Hand-picked from the 60 highest-population/highest-search-volume UK outcodes.
 * Each becomes a /[outcode] page and is included in the sitemap.
 */

export interface OutcodeMeta {
  code: string;
  name: string;
  region: string;
}

export const TOP_OUTCODES: OutcodeMeta[] = [
  { code: "SW1", name: "Westminster", region: "London" },
  { code: "E1", name: "Whitechapel", region: "London" },
  { code: "N1", name: "Islington", region: "London" },
  { code: "NW1", name: "Camden", region: "London" },
  { code: "SE1", name: "Southwark", region: "London" },
  { code: "W1", name: "Mayfair", region: "London" },
  { code: "EC1", name: "Clerkenwell", region: "London" },
  { code: "WC1", name: "Bloomsbury", region: "London" },
  { code: "M1", name: "Manchester city centre", region: "Greater Manchester" },
  { code: "M14", name: "Fallowfield", region: "Greater Manchester" },
  { code: "B1", name: "Birmingham city centre", region: "West Midlands" },
  { code: "B15", name: "Edgbaston", region: "West Midlands" },
  { code: "L1", name: "Liverpool city centre", region: "Merseyside" },
  { code: "LS1", name: "Leeds city centre", region: "West Yorkshire" },
  { code: "S1", name: "Sheffield city centre", region: "South Yorkshire" },
  { code: "BS1", name: "Bristol city centre", region: "Bristol" },
  { code: "NG1", name: "Nottingham city centre", region: "Nottinghamshire" },
  { code: "CV1", name: "Coventry city centre", region: "West Midlands" },
  { code: "NE1", name: "Newcastle city centre", region: "Tyne and Wear" },
  { code: "OX1", name: "Oxford city centre", region: "Oxfordshire" },
  { code: "OX11", name: "Didcot", region: "Oxfordshire" },
  { code: "CB1", name: "Cambridge", region: "Cambridgeshire" },
  { code: "CB2", name: "Trumpington", region: "Cambridgeshire" },
  { code: "BN1", name: "Brighton", region: "East Sussex" },
  { code: "BN2", name: "Kemptown", region: "East Sussex" },
  { code: "BA1", name: "Bath", region: "Somerset" },
  { code: "RG1", name: "Reading", region: "Berkshire" },
  { code: "RG14", name: "Newbury", region: "Berkshire" },
  { code: "GU1", name: "Guildford", region: "Surrey" },
  { code: "TN1", name: "Tunbridge Wells", region: "Kent" },
  { code: "ME1", name: "Rochester", region: "Kent" },
  { code: "CT1", name: "Canterbury", region: "Kent" },
  { code: "PO1", name: "Portsmouth", region: "Hampshire" },
  { code: "SO14", name: "Southampton", region: "Hampshire" },
  { code: "BH1", name: "Bournemouth", region: "Dorset" },
  { code: "PL1", name: "Plymouth", region: "Devon" },
  { code: "EX1", name: "Exeter", region: "Devon" },
  { code: "TR1", name: "Truro", region: "Cornwall" },
  { code: "GL1", name: "Gloucester", region: "Gloucestershire" },
  { code: "SN1", name: "Swindon", region: "Wiltshire" },
  { code: "SP1", name: "Salisbury", region: "Wiltshire" },
  { code: "MK1", name: "Milton Keynes", region: "Buckinghamshire" },
  { code: "AL1", name: "St Albans", region: "Hertfordshire" },
  { code: "WD1", name: "Watford", region: "Hertfordshire" },
  { code: "EN1", name: "Enfield", region: "Greater London" },
  { code: "IG1", name: "Ilford", region: "Greater London" },
  { code: "RM1", name: "Romford", region: "Greater London" },
  { code: "DA1", name: "Dartford", region: "Kent" },
  { code: "BR1", name: "Bromley", region: "Greater London" },
  { code: "CR0", name: "Croydon", region: "Greater London" },
  { code: "KT1", name: "Kingston upon Thames", region: "Greater London" },
  { code: "TW1", name: "Twickenham", region: "Greater London" },
  { code: "UB1", name: "Southall", region: "Greater London" },
  { code: "HA1", name: "Harrow", region: "Greater London" },
  { code: "WA1", name: "Warrington", region: "Cheshire" },
  { code: "CH1", name: "Chester", region: "Cheshire" },
  { code: "PR1", name: "Preston", region: "Lancashire" },
  { code: "DE1", name: "Derby", region: "Derbyshire" },
  { code: "LE1", name: "Leicester", region: "Leicestershire" },
  { code: "PE1", name: "Peterborough", region: "Cambridgeshire" },
  { code: "CF10", name: "Cardiff city centre", region: "Wales" },
  { code: "SA1", name: "Swansea", region: "Wales" },
  { code: "NP20", name: "Newport", region: "Wales" },
  // --- 2026-05 expansion (England & Wales only; data sources don't cover Scotland/NI) ---
  { code: "M20", name: "Didsbury", region: "Greater Manchester" },
  { code: "M21", name: "Chorlton", region: "Greater Manchester" },
  { code: "LS6", name: "Headingley", region: "West Yorkshire" },
  { code: "S11", name: "Ecclesall", region: "South Yorkshire" },
  { code: "BS6", name: "Redland", region: "Bristol" },
  { code: "B29", name: "Selly Oak", region: "West Midlands" },
  { code: "NG7", name: "Lenton", region: "Nottinghamshire" },
  { code: "LE2", name: "Clarendon Park", region: "Leicestershire" },
  { code: "CV5", name: "Earlsdon", region: "West Midlands" },
  { code: "NE2", name: "Jesmond", region: "Tyne and Wear" },
  { code: "SE15", name: "Peckham", region: "London" },
  { code: "E17", name: "Walthamstow", region: "London" },
  { code: "N4", name: "Finsbury Park", region: "London" },
  { code: "NW3", name: "Hampstead", region: "London" },
  { code: "SW11", name: "Battersea", region: "London" },
  { code: "SW19", name: "Wimbledon", region: "London" },
  { code: "W4", name: "Chiswick", region: "London" },
  { code: "E8", name: "Hackney", region: "London" },
  { code: "SE22", name: "East Dulwich", region: "London" },
  { code: "CR2", name: "South Croydon", region: "London" },
  { code: "BR2", name: "Bromley", region: "London" },
  { code: "KT2", name: "Kingston upon Thames", region: "Surrey" },
  { code: "TW2", name: "Twickenham", region: "London" },
  { code: "HA2", name: "Harrow", region: "London" },
  { code: "CO1", name: "Colchester", region: "Essex" },
  { code: "IP1", name: "Ipswich", region: "Suffolk" },
  { code: "NR1", name: "Norwich", region: "Norfolk" },
  { code: "YO1", name: "York", region: "North Yorkshire" },
  { code: "HU1", name: "Hull", region: "East Yorkshire" },
  { code: "HD1", name: "Huddersfield", region: "West Yorkshire" },
  { code: "BD1", name: "Bradford", region: "West Yorkshire" },
  { code: "WF1", name: "Wakefield", region: "West Yorkshire" },
  { code: "BL1", name: "Bolton", region: "Greater Manchester" },
  { code: "SK1", name: "Stockport", region: "Greater Manchester" },
  { code: "WN1", name: "Wigan", region: "Greater Manchester" },
  { code: "OL1", name: "Oldham", region: "Greater Manchester" },
  { code: "ST1", name: "Stoke-on-Trent", region: "Staffordshire" },
  { code: "WV1", name: "Wolverhampton", region: "West Midlands" },
  { code: "DY1", name: "Dudley", region: "West Midlands" },
  { code: "WS1", name: "Walsall", region: "West Midlands" },
  { code: "TF1", name: "Telford", region: "Shropshire" },
  { code: "WR1", name: "Worcester", region: "Worcestershire" },
  { code: "HR1", name: "Hereford", region: "Herefordshire" },
  { code: "GL50", name: "Cheltenham", region: "Gloucestershire" },
  { code: "TA1", name: "Taunton", region: "Somerset" },
  { code: "TQ1", name: "Torquay", region: "Devon" },
  { code: "SR1", name: "Sunderland", region: "Tyne and Wear" },
  { code: "TS1", name: "Middlesbrough", region: "Teesside" },
  { code: "DH1", name: "Durham", region: "County Durham" },
  { code: "LU1", name: "Luton", region: "Bedfordshire" },
];

export function getOutcode(code: string): OutcodeMeta | undefined {
  return TOP_OUTCODES.find((o) => o.code.toUpperCase() === code.toUpperCase());
}
